Финальный проект  - отказался от схемы 'products_published-value'  - поправил коннекторы  - поправил джобу

diff --git a/final/docker/kafka-connect/Dockerfile b/final/docker/kafka-connect/Dockerfile
--- a/final/docker/kafka-connect/Dockerfile
+++ b/final/docker/kafka-connect/Dockerfile
@@ -6,12 +6,15 @@ USER root
 COPY ./docker/kafka-connect/bin/ /tmp/bin/
 COPY ./docker/kafka-connect/share/ /tmp/share/
 
-# Устанавливаем коннектор со всеми зависимостями
+# Устанавливаем коннектор с retry (до 5 попыток)
 RUN echo "plugin.path=/usr/share/java,/usr/share/confluent-hub-components" > /tmp/worker.props \
-    && /tmp/bin/confluent-hub install --no-prompt \
+    && for i in 1 2 3 4 5; do \
+        /tmp/bin/confluent-hub install --no-prompt \
     confluentinc/kafka-connect-hdfs3:latest \
     --component-dir /usr/share/confluent-hub-components \
-    --worker-configs /tmp/worker.props
+        --worker-configs /tmp/worker.props \
+        && break || echo "Attempt $i failed, retrying..." && sleep 10; \
+    done
 
 # Права
 RUN chown -R appuser:appuser /usr/share/confluent-hub-components
